# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "annotation_processing"
description: Process genome annotation and quantify bulk RNA-seq data to select expressed isoforms for single-cell analysis
keywords:
  - annotation
  - isoform
  - salmon
  - quantification
  - gtf
components:
  - salmon/index
  - salmon/quant
input:
  - ch_samplesheet:
      type: file
      description: |
        Samplesheet channel with sample metadata and file paths
        Structure: [ val(meta), [ fastq_1, fastq_2, cranger_path ] ]
  - genome_fasta:
      type: file
      description: |
        Genome FASTA file
        Structure: [ path(genome.fa) ]
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
  - transcriptome_fasta:
      type: file
      description: |
        Transcriptome FASTA file
        Structure: [ path(transcriptome.fa) ]
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
  - genome_annotation:
      type: file
      description: |
        Genome annotation GTF file
        Structure: [ path(annotation.gtf) ]
      pattern: "*.gtf{,.gz}"
output:
  - all_transcripts:
      type: file
      description: |
        Selected isoforms GTF file
        Structure: [ path(transcripts.gtf) ]
      pattern: "*.gtf"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@Franzx7"
maintainers:
  - "@Franzx7"
